= strongswan-formula

https://travis-ci.com/saltstack-formulas/strongswan-formula[image:https://travis-ci.com/saltstack-formulas/strongswan-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

A SaltStack formula to install, configure and manage
https://www.strongswan.org/[Strongswan].

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Available states

=== `strongswan`

Meta-state (This is a state that includes other states)

This installs the strongswan package, configures and starts the
associated strongswan service.

=== `strongswan.install`

This state will install the strongswan package only.

=== `strongswan.config`

This state will configure the strongswan service and has a dependency on
`strongswan.install` via include list.

Configuration is splitted:::
  * for connections:
  ** in a main file for default options and [.title-ref]#%default#
  connection. This file include files from 'dropin' directory
  ** in a 'dropin' directory where each connection has its own config
  file
  * for secrets:
  ** in a main file which include files from 'dropin' directory
  ** in a 'dropin' directory where each connection has its own secret
  file

=== `strongswan.service`

This state manage the strongswan service.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `template` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
